### PR TITLE
Migrate to Python 3.6

### PR DESCRIPTION
**Pull request by mimischi**
Migrate the code base to Python 3. This PR introduces a second environment on Travis-CI, building the app and running all tests in Python 3.

In the long run we want to get rid of Python 2, so we'll remove the first environment again. We should aim to convert the whole app to a Python 3 only project.

## Things To-Do

- [x] Exchange all instances of `unicode` with `str`
- [x] Make sure `dict` iterations are correct (should be)
- [x] Check the [official porting documentation](https://docs.python.org/3/howto/pyporting.html)

### CODE REVIEW

**Comment by mimischi** [comment]
Echt cool, dass man Travis-CI so einfach dazu kriegen kann in verschiedenen Python Environments zu bauen. Das Projekt lässt sich zumindest mit Python 3.6 bauen, allerdings wissen wir aktuell noch nicht, ob das bisher etablierte auch funktioniert. Dafür müssen Unit tests her.

**Comment by chgad** [comment]
Whats meant by "change all unicode instances" ?

**Comment by mimischi** [comment]
There is no `unicode` anymore, [see here](https://docs.python.org/3/howto/pyporting.html#text-versus-binary-data).

**Comment by mimischi** [comment]
The PR is ready from my side. @chgad any objections?

**Comment by chgad** [comment]
Everything ok.

**Pull request merged**
